# Generated by Django 4.1.13 on 2024-05-17 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ry', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExampleModel',
        ),
    ]
