# Generated by Django 4.1.13 on 2024-05-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ry', '0002_delete_examplemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('sub', models.CharField(max_length=255)),
            ],
        ),
    ]
