# Generated by Django 4.1.13 on 2024-05-20 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ry', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
