# Generated by Django 4.1.13 on 2024-05-20 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ry', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='goal',
        ),
    ]
