# Generated by Django 4.2.11 on 2024-05-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ry', '0006_rename_userprofile_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
